---
- hosts: dbservers
  become: true
  become_user: root
  pre_tasks:
    - name: Install Dependencies
      package:
        name: 'acl'
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Galaxy dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'tar', 'python3-venv', 'python3-setuptools', 'python3-pip']
    - name: Install docker pip package
      ansible.builtin.pip:
        name: docker
    - name: Install RHEL/CentOS/Rocky specific dependencies
      package:
        name: ['tmpwatch']
      when: ansible_os_family == 'RedHat'
    - name: Install Debian/Ubuntu specific dependencies
      package:
        name: ['tmpreaper']
      when: ansible_os_family == 'Debian'
    - name: Make scATAC preprocessing toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/scATAC_processing
        state: directory
    - name: Make ArchR toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/ArchR_tools
        state: directory
    - name: Make Gatk4 toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/gatk4
        state: directory
    - name: Make ScriptManager toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/ScriptManager
        state: directory
    - name: Make PEGR toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/PEGR
        state: directory
    - name: Make ChIP toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/ChIP_tools
        state: directory
    - name: Make ScriptManager toolkit destination dir
      file:
        path: /cephfs/galaxy/local_tools/ScriptManager
        state: directory
  roles:
    - galaxyproject.tusd
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.galaxy
    - usegalaxy_eu.tpv_auto_lint
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
    - galaxyproject.nginx
    - geerlingguy.docker
    - usegalaxy_eu.rabbitmqserver
    - galaxyproject.gxadmin
#    - galaxyproject.cvmfs
  post_tasks:
    - name: Copy tool config file for galaxy
      copy:
        src: templates/galaxy/config/local_tool_conf.xml
        dest: "{{ galaxy_root }}/config/local_tool_conf.xml"
    - name: Setup gxadmin cleanup task
      ansible.builtin.cron:
        name: "Cleanup Old User Data"
        user: galaxy # Run as the Galaxy user
        minute: "0"
        hour: "0"
        job: "GALAXY_LOG_DIR=/tmp/gxadmin/ GALAXY_ROOT={{ galaxy_root }}/server /usr/local/bin/gxadmin galaxy cleanup 60"
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
