# NOTE: Use dashes (-) exclusively for tags and underscores (_) exclusively for destinations.
destinations:
  local_env:
    runner: local_runner
    max_accepted_cores: 1
    params:
      tmp_dir: true
  local_slurm:
    runner: slurm_runner
    max_accepted_cores: 8
    max_accepted_mem: 24
    walltime: 8
    scheduling:
      require:
        - local-slurm
  pulsar_psu_tpv:
    runner: pulsar_psu_runner
    params:
      default_file_action: remote_transfer
      dependency_resolution: remote
      jobs_directory: /storage/group/bfp2/default/00_pughlab/pulsar/files/staging
      persistence_directory: /storage/group/bfp2/default/00_pughlab/pulsar/files/persisted_data
      remote_metadata: false
      rewrite_parameters: true
      transport: curl
      outputs_to_working_directory: false
    scheduling:
      require:
        - psu-pulsar
  pulsar_iu_tpv:
    runner: pulsar_iu_runner
    params:
      default_file_action: remote_transfer
      dependency_resolution: remote
      jobs_directory: /storage/group/bfp2/default/00_pughlab/pulsar/files/staging
      persistence_directory: /storage/group/bfp2/default/00_pughlab/pulsar/files/persisted_data
      remote_metadata: false
      rewrite_parameters: true
      transport: curl
      outputs_to_working_directory: false
    scheduling:
      require:
        - iu-pulsar
