global:
  default_inherits: default

tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 4
    params:
      tmp_dir: true
      nativeSpecification: "--nodes=1 --cpus-per-task={cores}"
    scheduling:
      prefer:
        - local-slurm

  .*/fastqc/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/bwa*/.*:
    cores: 4
    mem: 16
    params:
      nativeSpecification: "--nodes=1 --ntasks=1 --cpus-per-task={cores}"
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/picard/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/samtools_filter/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/*deeptools*/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/*bedtools*/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/*repeat_masker*/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/*meme*/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
