tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 4
    params:
      walltime: 8
  .*testing.*:
    cores: 2
    mem: cores * 4
    rules:
      - id: admin_only_testing_tool
        if: |
          # Only allow the tool to be executed if the user is an admin
          admin_users = app.config.admin_users
          # last line in block must evaluate to a value - which determines whether the TPV if conditional matches or not
          not user or user.email not in admin_users
        fail: Unauthorized. Only admins can execute this tool.
      - id: resource_params_defined
        if: |
          param_dict = job.get_param_values(app)
          param_dict.get('__job_resource', {}).get('__job_resource__select') == 'yes'
        cores: int(job.get_param_values(app)['__job_resource']['cores'])
        params:
           walltime: "{int(job.get_param_values(app)['__job_resource']['time'])}"
#  .*/bwa/.*:
#    scheduling:
#      require:
#        - psu-pulsar
  .*/bwa*/.*:
    scheduling:
      require:
        - iu-pulsar
  .*/fastqc/.*:
    scheduling:
      require:
        - iu-pulsar
  .*/*repeat_masker*/.*:
    scheduling:
      require:
        - iu-pulsar
