global:
  default_inherits: default

tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 4
    params:
      tmp_dir: true
      submit_native_specification: "--account=open --time=8:00:00 --nodes=1 --cpus-per-task={cores}"
    scheduling:
      prefer:
        - local-slurm

  .*/fastqc/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/bwa*/.*:
    cores: 8
    mem: 32
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/picard/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/samtools_filter/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/*bedtools*/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/*repeat_masker*/.*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/deeptools*/*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/meme_meme/*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/meme_fimo/*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
  .*/scriptmanager_bam-to-scidx/*:
    scheduling:
      require:
        - psu-pulsar
#        - iu-pulsar
