global:
  default_inherits: default

tools:
  default:
    cores: 1
    mem: cores * 4
    params:
      tmp_dir: true
      nativeSpecification: "--nodes=1 --cpus-per-task={cores}"
    scheduling:
      prefer:
        - local-slurm

  .*/bwa*/.*:
    scheduling:
      require:
#        - psu-pulsar
        - iu-pulsar
  .*/fastqc/.*:
    scheduling:
      require:
        - iu-pulsar
  .*/*repeat_masker*/.*:
    scheduling:
      require:
        - iu-pulsar
